/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EdoRes;
import Controller.Historico;
import Controller.Secretaria;
import Controller.Utilidades;
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
/**
 *
 * @author lenovo
 */
public class DialogoEstadoResultados extends javax.swing.JDialog {
 private TableModel modelo;
    /**
     * Creates new form DialogoEstadoResultados
     */
    public DialogoEstadoResultados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        llenarCmbPeriodos();
        
    }
    
       private void llenarCmbPeriodos(){
           Historico h = new Historico();
           h.buscaPeriodos();
           String[] periodos = h.getPeriodos();
           cmbPeriodo.setModel(new DefaultComboBoxModel((Object[]) periodos));
           cmbPeriodo.setSelectedIndex(h.getNumeroPeriodos()-1);
    }
    
    private void personalizaTablaEdoRes() {
         //cambiar colores de tabla
           tblEdoRes.getTableHeader().setVisible(false);
       tblEdoRes.setDefaultRenderer(Object.class, 
               new DefaultTableCellRenderer(){
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column){
                        
                               if(row%2 == 0){
                                   setBackground(Color.decode("#DFF7FF")); setForeground(Color.BLACK);
                               }else{
                                   setBackground(Color.decode("#CEE7EF")); setForeground(Color.BLACK);
                               }
                            if(column == 2){
                                this.setHorizontalAlignment(SwingConstants.RIGHT);
                            }else{
                                this.setHorizontalAlignment(SwingConstants.LEFT);
                            }
                            
                       super.getTableCellRendererComponent(table, value, selected, focused, row, column);
                       return this;
                    }
               });
        tblEdoRes.setRowHeight(40);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdoRes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblEdoRes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblEdoRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEdoRes);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Estado de Resultados");

        cmbPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPeriodoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Periodo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(49, 49, 49)
                                .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeriodoActionPerformed
        EdoRes edo = new EdoRes(cmbPeriodo.getSelectedItem().toString());
        this.tblEdoRes.setModel(edo.creaModeloEdoRes());
        personalizaTablaEdoRes();
    }//GEN-LAST:event_cmbPeriodoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEdoRes;
    // End of variables declaration//GEN-END:variables
}
