/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.BoxLayout;
import static javax.swing.BoxLayout.X_AXIS;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.text.View;

/**
 *
 * @author toshiba
 */
public class DialogoPersonalizado extends javax.swing.JDialog {
    private int x;
    private int y;

    /**
     * Creates new form DialogoPersonalizado
     */
    public DialogoPersonalizado(String cadena, boolean modal) {
        super((Frame)null, modal);
        
        cerrar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(612, 331));
        setSize(new java.awt.Dimension(612, 331));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        cerrar.setText("X");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloMouseDragged(evt);
            }
        });
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloMousePressed(evt);
            }
        });
        
       // titulo.setBounds(getLocation().x, getLocation().y, getWidth(), 40);
        //cerrar.setBounds(getLocation().x, getLocation().y+getWidth()-40, 30, 30);
       //titulo.setBounds(0,0, getWidth(), 40);
  //     cerrar.setBounds(0,0, 35, 35);
       //panel.setBounds(-20, 50, getWidth(),getHeight());
        titulo.setForeground(Color.white);
        titulo.setText(cadena);
        titulo.setBackground(Color.darkGray);
        titulo.setOpaque(true);
        titulo.setFocusable(false);
        cerrar.setFocusable(false);
        titulo.setHorizontalAlignment(SwingConstants.CENTER);
        titulo.setLayout(new BoxLayout(titulo, X_AXIS));
        titulo.add(cerrar,RIGHT_ALIGNMENT);
        getContentPane().setLayout(new BorderLayout()); // contenedor de 5 partes
        
        titulo.setFont(new Font(Font.SANS_SERIF,1,16));
        add(titulo,BorderLayout.NORTH);
        
       
        //add(panel);
  //      setLocationRelativeTo(getContentPane());
    //    Point p = getLocation();
      //  contenedor.setLocation(p.x,p.y+10);
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    
    

    /*public JPanel getContenedor() {
        return contenedor;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(612, 331));
        setSize(new java.awt.Dimension(612, 331));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setText("X");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 36, -1));

        titulo.setBackground(new java.awt.Color(77, 77, 77));
        titulo.setText("titulo");
        titulo.setOpaque(true);
        titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloMouseDragged(evt);
            }
        });
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloMousePressed(evt);
            }
        });
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 29));

        jScrollPane1.setAlignmentX(50.0F);
        jScrollPane1.setAlignmentY(50.0F);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(612, 378));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(612, 378));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 296));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_tituloMousePressed

    private void tituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        setLocation(punto.x - x,punto.y - y);
    }//GEN-LAST:event_tituloMouseDragged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        titulo.setSize(getWidth(), titulo.getHeight());
        Point punto = cerrar.getLocation();
        cerrar.setLocation(titulo.getLocation().x+titulo.getWidth()-40,punto.y);
         //     panel.setBounds(0, 50, getWidth(),getHeight());
//        contenedor.setSize(getWidth(),getHeight());
//        Point p = getLocation();
  //      contenedor.setLocation(p.x-200,p.y-100);
    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    void setjScrollPane1(JPanel panel) {
        
        jScrollPane1 = new JScrollPane(panel);
        getContentPane().add(jScrollPane1, BorderLayout.CENTER);
    }
}
