/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Secretaria;
import Controller.Utilidades;
import Controller.Vendedor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;
/**
 *
 * @author lenovo
 */
public class DialogoAdminEmpleados extends javax.swing.JDialog {
private TableModel modeloTabla ;
    /**
     * Creates new form DialogoAdminEmpleados
     */
    public DialogoAdminEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); Vendedor vend = new Vendedor();        
        modeloTabla = vend.obtenerTablaVend();
        tablaVendedor.setModel(modeloTabla);
        titulosTabla();     
    }
    
     private void titulosTabla(){
        tablaVendedor.getColumn(tablaVendedor.getColumnName(0)).setHeaderValue(" ");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(1)).setHeaderValue("Nombre");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(2)).setHeaderValue("Salario");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(3)).setHeaderValue("%Comisión");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(4)).setHeaderValue("#Ventas");

        
        tablaVendedor.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaVendedor.getColumnModel().getColumn(0).setMinWidth(0);
        tablaVendedor.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaVendedor.setRowHeight(30);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("Agregar");

        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Salario", "% Comision", "# ventas"
            }
        ));
        jScrollPane1.setViewportView(tablaVendedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVendedor;
    // End of variables declaration//GEN-END:variables
}
