/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Almacen;
import Controller.Cliente;
import Controller.Producto;
import Controller.Secretaria;
import Controller.Utilidades;
import Controller.Vendedor;
import Controller.Venta;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class DialogoRegistrarVenta extends javax.swing.JDialog {
 private Cliente cliente;
    private TableModel modeloTabla1;
    private TableModel modeloTabla2;
    private Venta v;
    private List <Producto> productos; 
    private Double precioPersonalizado;
    private Vendedor vend;
    /**
     * Creates new form DialogoRegistrarVenta
     */
    public DialogoRegistrarVenta(java.awt.Frame parent, boolean modal,String idCliente, Vendedor vendedor) {
        super(parent, modal);
        initComponents();cliente = new Cliente(idCliente);
        Almacen a = new Almacen();
        a.obtenerProductos();
        this.productos = a.getProductos();
        modeloTabla1 = a.creaModeloProdV1(productos.size());
        tablaProd.setModel(modeloTabla1);
        titulosTabla();
        v = new Venta();      
        v.setVendedor(vendedor.getNombre());
        this.vend = vendedor;
        chNombre.setSelected(true);
        txtBuscar.requestFocus();
    }
    
    private void titulosTabla(){
        tablaProd.getColumn(tablaProd.getColumnName(0)).setHeaderValue(" ");
        tablaProd.getColumn(tablaProd.getColumnName(1)).setHeaderValue("Nombre");
        tablaProd.getColumn(tablaProd.getColumnName(2)).setHeaderValue("Marca");
        tablaProd.getColumn(tablaProd.getColumnName(3)).setHeaderValue("Tipo");
        tablaProd.getColumn(tablaProd.getColumnName(4)).setHeaderValue("Cantidad");
        tablaProd.getColumn(tablaProd.getColumnName(5)).setHeaderValue("Precio C");
        tablaProd.getColumn(tablaProd.getColumnName(6)).setHeaderValue("Precio V");
         tablaProd.getColumn(tablaProd.getColumnName(7)).setHeaderValue("pedido");
         
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaProd.setRowHeight(40);
       /* 
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(0).setPreferredWidth(0);*/
    }
    
     private void titulosTabla2(){
        tablaVenta.getColumn(tablaVenta.getColumnName(0)).setHeaderValue(" ");
        tablaVenta.getColumn(tablaVenta.getColumnName(1)).setHeaderValue("Nombre");
        tablaVenta.getColumn(tablaVenta.getColumnName(2)).setHeaderValue("Marca");
        tablaVenta.getColumn(tablaVenta.getColumnName(3)).setHeaderValue("Tipo");
        tablaVenta.getColumn(tablaVenta.getColumnName(4)).setHeaderValue("Cantidad");
        tablaVenta.getColumn(tablaVenta.getColumnName(5)).setHeaderValue("Precio unitario");
        tablaVenta.getColumn(tablaVenta.getColumnName(6)).setHeaderValue("Precio neto");
        tablaVenta.getColumn(tablaVenta.getColumnName(7)).setHeaderValue("Pedido");
         
        tablaVenta.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setMinWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaVenta.setRowHeight(40);

        /*
        tablaVenta.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setMinWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setPreferredWidth(0);*/
    }
public void setPrecioPersonalizado(Double precioPersonalizado) {
        this.precioPersonalizado = precioPersonalizado;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNeto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        chNombre = new javax.swing.JRadioButton();
        chCodigo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        btnMostrarTodo = new javax.swing.JButton();
        btnCompletar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCompletar1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        chkPrecio = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNeto.setText("0.0");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Tipo", "Cantidad", "Precio C", "Precio V"
            }
        ));
        jScrollPane1.setViewportView(tablaProd);

        chNombre.setText("Nombre");
        chNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNombreActionPerformed(evt);
            }
        });

        chCodigo.setText("Código");
        chCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCodigoActionPerformed(evt);
            }
        });

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Tipo", "Cantidad", "Precio unitario", "Precio neto"
            }
        ));
        tablaVenta.setToolTipText("");
        jScrollPane2.setViewportView(tablaVenta);

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnCompletar.setText("Completar");
        btnCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCompletar1.setText("Cancelar");
        btnCompletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletar1ActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        chkPrecio.setText("cambiar precio");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Carrito:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(186, 186, 186)
                        .addComponent(chkPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(lblNeto)
                        .addGap(298, 298, 298)
                        .addComponent(btnCompletar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCompletar1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(chNombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnBuscar)
                        .addGap(184, 184, 184)
                        .addComponent(btnMostrarTodo)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chNombre)
                            .addComponent(chCodigo)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostrarTodo)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkPrecio)
                        .addComponent(jLabel1)
                        .addComponent(btnQuitar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNeto))
                        .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCompletar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNombreActionPerformed
        chCodigo.setSelected(false);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chNombreActionPerformed

    private void chCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCodigoActionPerformed
        chNombre.setSelected(false);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chCodigoActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        Almacen a = new Almacen();
        a.setProductos(productos);
        modeloTabla1 = a.creaModeloProdV1(productos.size());
        tablaProd.setModel(modeloTabla1);
        titulosTabla();
        txtBuscar.setText("");
        txtBuscar.requestFocus();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarActionPerformed
        v.setCostoVenta(v.getCostoVenta());
        v.setNeto(v.getNeto());
        v.setIdCl(cliente.getId());

        if(v.registrarVenta()){ //se registra venta
            Almacen a = new Almacen();
            a.actualizarProducto(this.productos); // se actualizan las cantidades en almacen
            cliente.actualizarSaldo(v.getNeto(),this.cliente,'c'); // se actualiza el saldo del cliente
            vend.actualizaVentas(vend);
            JOptionPane.showOptionDialog(this, "Venta finalizada", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
            dispose();
        }else{
            JOptionPane.showOptionDialog(this, "Agregue productos", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
        }
    }//GEN-LAST:event_btnCompletarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-, ,]{1,50})$",txtBuscar.getText())){
            if(chNombre.isSelected()){
                Almacen a = new Almacen();
                a.buscarPorNombre(txtBuscar.getText());
                for(Producto p : a.getProductos()){
                    for(Producto p1 : productos){
                        if(p.getId().equals(p1.getId())){
                            p.setCantidad(p1.getCantidad());
                        }
                    }
                }
                this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
                tablaProd.setModel(modeloTabla1);
                titulosTabla();

            }else if(chCodigo.isSelected()){
                Almacen a = new Almacen();
                a.buscarPorCodigoB(txtBuscar.getText());
                for(Producto p : a.getProductos()){
                    for(Producto p1 : productos){
                        if(p.getId().equals(p1.getId())){
                            p.setCantidad(p1.getCantidad());
                        }
                    }
                }
                this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
                tablaProd.setModel(modeloTabla1);
                titulosTabla();

            }else{
                JOptionPane.showOptionDialog(this, "Seleccione una opción", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
            }

        }else{
            JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCompletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletar1ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Desea cancelar la venta ?", "Seleccione una opción", JOptionPane.YES_NO_OPTION) == 0){
            dispose();
        }
    }//GEN-LAST:event_btnCompletar1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(chNombre.isSelected()){
                Almacen a = new Almacen();
                a.buscarPorNombre(txtBuscar.getText());
                for(Producto p : a.getProductos()){
                    for(Producto p1 : productos){
                        if(p.getId().equals(p1.getId())){
                            p.setCantidad(p1.getCantidad());
                        }
                    }
                }
                this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
                tablaProd.setModel(modeloTabla1);
                titulosTabla();

            }else if(chCodigo.isSelected()){
                Almacen a = new Almacen();
                a.buscarPorCodigoB(txtBuscar.getText());
                for(Producto p : a.getProductos()){
                    for(Producto p1 : productos){
                        if(p.getId().equals(p1.getId())){
                            p.setCantidad(p1.getCantidad());
                        }
                    }
                }
                this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
                tablaProd.setModel(modeloTabla1);
                titulosTabla();
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(tablaProd.getSelectedRow() != -1){
            Integer fila = tablaProd.getSelectedRow();
            if(Integer.parseInt(tablaProd.getValueAt(fila, 4).toString()) > 0){
                if(chkPrecio.isSelected()){
                    this.precioPersonalizado = Double.parseDouble(JOptionPane.showInputDialog (this, "Precio de venta: ", "Precio personalizado",JOptionPane.INFORMATION_MESSAGE));
                    v.agregarAlCarrito(tablaProd.getValueAt(fila, 0).toString(),this.precioPersonalizado);
                }else{
                    v.agregarAlCarrito(tablaProd.getValueAt(fila, 0).toString());
                }
                modeloTabla2 = v.creaModTblList(v.getListaV().size());
                tablaVenta.setModel(modeloTabla2);
                titulosTabla2();
                lblNeto.setText(v.getNeto().toString());

                for(Producto p1 : productos){
                    if(p1.getId().equals(tablaProd.getValueAt(fila, 0).toString())){
                        p1.setCantidad(p1.getCantidad()-1);
                    }
                }
                Almacen a = new Almacen();
                a.setProductos(productos);
                modeloTabla1 = a.creaModeloProdV1(productos.size());
                tablaProd.setModel(modeloTabla1);
                titulosTabla();
                txtBuscar.setText("");
                txtBuscar.requestFocus();
            }else{
                JOptionPane.showOptionDialog(this, "No hay más existencia", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
        else{
            JOptionPane.showOptionDialog(this, "Seleccione un producto", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        if(tablaVenta.getSelectedRow() != -1){
            Integer fila = tablaVenta.getSelectedRow();
            v.quitarDlCarrito(tablaVenta.getValueAt(fila, 0).toString());
            modeloTabla2 = v.creaModTblList(v.getListaV().size());
            lblNeto.setText(v.getNeto().toString());
            for(Producto p1 : productos){
                if(p1.getId().equals(tablaVenta.getValueAt(fila, 0).toString())){
                    p1.setCantidad(p1.getCantidad()+1);
                }
            }
            Almacen a = new Almacen();
            a.setProductos(productos);
            modeloTabla1 = a.creaModeloProdV1(productos.size());

            tablaVenta.setModel(modeloTabla2);
            titulosTabla2();
            tablaProd.setModel(modeloTabla1);
            titulosTabla();
        }
        else{
            JOptionPane.showOptionDialog(this, "Seleccione un producto de la venta", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
        }
    }//GEN-LAST:event_btnQuitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCompletar;
    private javax.swing.JButton btnCompletar1;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JRadioButton chCodigo;
    private javax.swing.JRadioButton chNombre;
    private javax.swing.JRadioButton chkPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNeto;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
