/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.regex.Pattern;
import Controller.Almacen;
import Controller.Pedido;
import Controller.Producto;
import Controller.Proveedor;
import Controller.Secretaria;
import Controller.TablaAlmacen;
import Controller.Utilidades;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class DialogoInventario extends javax.swing.JDialog {
    private VentanaPrincipal vp;
    private Almacen almacen;
    private Pedido pedido;
    
    private TableModel modeloTabla;
    private Proveedor prov;

    /**
     * Creates new form DialogoInventario
     */
    public DialogoInventario(boolean modal, VentanaPrincipal vp) {
        super(vp, modal);
        initComponents();
        almacen = vp.getAlmacen();
        modeloTabla = creaModeloProdA(almacen.getProductos());
        tablaProd.setModel(modeloTabla);
        tablaProd.setOpaque(false);
        titulosTabla();
        
        pedido = vp.getPedido();
        llenarCmbPed(pedido.getPedidos());
        chNombre.setSelected(true);
        txtBuscar.requestFocus();
        
        prov = vp.getProveedor();
        llenarCmbProv(prov.getProveedores());
        
    }

    private void llenarCmbProv(List<Proveedor> proveedores) {
        String[] cadena = new String[proveedores.size() + 1];
        int i = 1;
        cadena[0] = "Todos";
        for (Proveedor p : proveedores) {
            cadena[i] = p.getRazonSocial();
            i++;
        }
        cmbProv.setModel(new DefaultComboBoxModel((Object[]) cadena));
    }

    private void llenarCmbPed(List<Pedido> pedidos) {
        String[] cadena = new String[pedidos.size() + 1];
        int i = 1;
        cadena[0] = "todo";
        for (Pedido p : pedidos) {
            cadena[i] = p.getId().toString();
            i++;
        }
        cmbPedido.setModel(new DefaultComboBoxModel((Object[]) cadena));
    }

    private void titulosTabla() {
        tablaProd.getColumn(tablaProd.getColumnName(0)).setHeaderValue(" ");
        tablaProd.getColumn(tablaProd.getColumnName(1)).setHeaderValue("Nombre");
        tablaProd.getColumn(tablaProd.getColumnName(2)).setHeaderValue("Marca");
        tablaProd.getColumn(tablaProd.getColumnName(3)).setHeaderValue("Tipo");
        tablaProd.getColumn(tablaProd.getColumnName(4)).setHeaderValue("Cantidad");
        tablaProd.getColumn(tablaProd.getColumnName(5)).setHeaderValue("Precio C");
        tablaProd.getColumn(tablaProd.getColumnName(6)).setHeaderValue("Precio V");
        tablaProd.getColumn(tablaProd.getColumnName(7)).setHeaderValue("Pedido");

        tablaProd.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaProd.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        chNombre = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbPedido = new javax.swing.JComboBox();
        chCodigo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarTodo = new javax.swing.JButton();
        cmbProv = new javax.swing.JComboBox();
        cmbPedido1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        chNombre.setText("Nombre");
        chNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Pedido:");

        cmbPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPedidoActionPerformed(evt);
            }
        });

        chCodigo.setText("Código");
        chCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Proveedor:");

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        cmbProv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvActionPerformed(evt);
            }
        });

        cmbPedido1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPedido1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        jButton1.setText("Dar de baja producto");

        jButton2.setText(">Excel");

        jButton3.setText("PDF");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3))
                                    .addComponent(chCodigo))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cmbPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chNombre))
                                .addGap(50, 50, 50)
                                .addComponent(btnBuscar)
                                .addGap(36, 36, 36)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbProv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton2)
                        .addGap(15, 15, 15)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addComponent(chCodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(chNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBuscar)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(cmbProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnMostrarTodo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
          if (chCodigo.isSelected()) {
                if (Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-]{1,50})$", txtBuscar.getText())) {
                    modeloTabla = creaModeloProdA(almacen.buscarPorCodigoB(txtBuscar.getText()));
                    tablaProd.setModel(modeloTabla);
                    titulosTabla();
                } else {
                    JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "}, "OK");
                }

            } else if (chNombre.isSelected()) {
                if (Pattern.matches("^(([A-Z,Ñ,ñ,a-z,-]{1,30})([ ]{0,1})*){1,6}$", txtBuscar.getText())) {
                    modeloTabla = creaModeloProdA(almacen.buscarPorNombre(txtBuscar.getText()));
                    tablaProd.setModel(modeloTabla);
                    titulosTabla();
                } else {
                    JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "}, "OK");
                }
            }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNombreActionPerformed
        chCodigo.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chNombreActionPerformed

    private void cmbPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPedidoActionPerformed
        System.out.println(cmbPedido.getSelectedIndex());
        if (cmbPedido.getSelectedIndex() == 0) {
            modeloTabla = creaModeloProdA(almacen.getProductos());
            tablaProd.setModel(modeloTabla);
            titulosTabla();
        } else {
            String id = pedido.getPedidos().get(cmbPedido.getSelectedIndex() - 1).getId().toString();
            modeloTabla =creaModeloProdA(almacen.buscarPorPedido(id));
            tablaProd.setModel(modeloTabla);
            titulosTabla();
        }
    }//GEN-LAST:event_cmbPedidoActionPerformed
private TableModel creaModeloProdA(List<Producto> productos) {
        Integer filas = productos.size();
        TablaAlmacen modelo1 = new TablaAlmacen(filas);  //numero de filas del ResultSet como parametro del constructor
        int i = 0;
        Utilidades uts = new Utilidades();
        for (Producto p1 : productos) {
            modelo1.setValueAt(p1.getId(), i, 0);
            modelo1.setValueAt(p1.getNombre(), i, 1);
            modelo1.setValueAt(p1.getMarca(), i, 2);
            modelo1.setValueAt(p1.getTipo(), i, 3);
            modelo1.setValueAt(p1.getCantidad().toString(), i, 4);
            modelo1.setValueAt(uts.formatDinero(p1.getPrecioC()), i, 5);
            modelo1.setValueAt(uts.formatDinero(p1.getPrecioV()), i, 6);
            modelo1.setValueAt(p1.getIdPedido().toString(), i, 7);
            i++;
        }
       
        return modelo1;
    }
    private void chCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCodigoActionPerformed
        chNombre.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chCodigoActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        modeloTabla = creaModeloProdA(almacen.getProductos());
        tablaProd.setModel(modeloTabla);
        titulosTabla();
        txtBuscar.setText("");
        cmbPedido.setSelectedIndex(0);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void cmbProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvActionPerformed
        if (cmbProv.getSelectedIndex() != 0) {
            
            almacen.buscarPorProv(cmbProv.getSelectedItem().toString(),pedido);
            modeloTabla = a.creaModeloProdA(a.getProductos().size());
            tablaProd.setModel(modeloTabla);
            titulosTabla();
        }
    }//GEN-LAST:event_cmbProvActionPerformed

    private void cmbPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPedido1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JRadioButton chCodigo;
    private javax.swing.JRadioButton chNombre;
    private javax.swing.JComboBox cmbPedido;
    private javax.swing.JComboBox cmbPedido1;
    private javax.swing.JComboBox cmbProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
