/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Almacen;
import Controller.Producto;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author lenovo
 */
public class DialogoAgregarProd extends javax.swing.JDialog {
    private boolean datosValidos;
    private DialogoRegistrarPedido vReg;
    private String codigoB;
    private Producto prod;

    /**
     * Creates new form DialogoAgregarProd
     */
    public DialogoAgregarProd(java.awt.Frame parent, boolean modal,DialogoRegistrarPedido vReg, String cod) {
        super(parent, modal);
        initComponents();
         this.vReg = vReg;
        this.codigoB = cod;
        if (vReg.getProv().getRazonSocial().equals("Mary Kay")) {
            this.txtMarca.setText("Mary Kay");
            this.txtPrecioV.setText("00");
            this.cmbTipo.setSelectedIndex(3);
        }

        datosValidos = false;
        radStock_no.setSelected(true);
        radStock_si.setSelected(false);
        stockMin.setEnabled(false);
        txtCodigo.setText(cod);
        txtCodigo.setEnabled(false);
    }
    public DialogoAgregarProd(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        this.vReg = null;
        datosValidos = false;
        radStock_no.setSelected(true);
        radStock_si.setSelected(false);
        stockMin.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        radStock_si = new javax.swing.JRadioButton();
        txtPrecioC = new javax.swing.JTextField();
        radStock_no = new javax.swing.JRadioButton();
        txtPrecioV = new javax.swing.JTextField();
        stockMin = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarcaKeyReleased(evt);
            }
        });

        jLabel3.setText("Precio Compra:");

        jLabel2.setText("Tipo:");

        jLabel4.setText("Precio Venta:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "perfume", "bolsa", "cartera", "cosmetico", "reloj", "joyeria" }));

        jLabel5.setText("Cantidad:");

        jLabel7.setText("Stock mínimo:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        radStock_si.setText("Si");
        radStock_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStock_siActionPerformed(evt);
            }
        });

        txtPrecioC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioCKeyReleased(evt);
            }
        });

        radStock_no.setText("No");
        radStock_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStock_noActionPerformed(evt);
            }
        });

        txtPrecioV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioVKeyReleased(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });

        jLabel8.setText("Código:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca:");

        jLabel1.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radStock_si)
                                        .addGap(18, 18, 18)
                                        .addComponent(radStock_no))
                                    .addComponent(stockMin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                            .addComponent(txtPrecioV, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrecioC, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(144, 144, 144)
                                    .addComponent(txtCodigo))))
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(radStock_si)
                    .addComponent(radStock_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyReleased
        if (Pattern.matches("^(([A-Z,Ñ,ñ,a-z,0-9]{2,30})+([ ]{0,1})){1,5}$", txtMarca.getText())) {
            txtMarca.setBackground(Color.GREEN);
            txtMarca.setForeground(Color.BLACK);
            this.datosValidos = true;
        } else {
            txtMarca.setForeground(Color.WHITE);
            txtMarca.setBackground(Color.RED);
            this.datosValidos = false;
        }
    }//GEN-LAST:event_txtMarcaKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if (Pattern.matches("^(([A-Z,Ñ,ñ,a-z,0-9]{2,30})+([ ]{0,1})){1,10}$", txtNombre.getText())) {
            txtNombre.setBackground(Color.GREEN);
            txtNombre.setForeground(Color.BLACK);
            this.datosValidos = true;
        } else {
            txtNombre.setForeground(Color.WHITE);
            txtNombre.setBackground(Color.RED);
            this.datosValidos = false;
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void radStock_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radStock_siActionPerformed
        stockMin.setEnabled(true);
        radStock_no.setSelected(false);
    }//GEN-LAST:event_radStock_siActionPerformed

    private void txtPrecioCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCKeyReleased
        if (Pattern.matches("^([0-9]{2,4})(([.])([0-9]{2}))*$", txtPrecioC.getText())) {
            txtPrecioC.setBackground(Color.GREEN);
            txtPrecioC.setForeground(Color.BLACK);
            this.datosValidos = true;
        } else {
            txtPrecioC.setForeground(Color.WHITE);
            txtPrecioC.setBackground(Color.RED);
            this.datosValidos = false;
        }
    }//GEN-LAST:event_txtPrecioCKeyReleased

    private void radStock_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radStock_noActionPerformed
        stockMin.setEnabled(false);
        radStock_si.setSelected(false);
    }//GEN-LAST:event_radStock_noActionPerformed

    private void txtPrecioVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVKeyReleased
        if (Pattern.matches("^([0-9]{2,4})(([.])([0-9]{2}))*$", txtPrecioV.getText())) {
            txtPrecioV.setBackground(Color.GREEN);
            txtPrecioV.setForeground(Color.BLACK);
            this.datosValidos = true;
        } else {
            txtPrecioV.setForeground(Color.WHITE);
            txtPrecioV.setBackground(Color.RED);
            this.datosValidos = false;
        }
    }//GEN-LAST:event_txtPrecioVKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        if (Pattern.matches("^([0-9]{1,3})$", txtCantidad.getText())) {
            txtCantidad.setBackground(Color.GREEN);
            txtCantidad.setForeground(Color.BLACK);
            this.datosValidos = true;
        } else {
            txtCantidad.setForeground(Color.WHITE);
            txtCantidad.setBackground(Color.RED);
            this.datosValidos = false;
        }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (datosValidos) {
            if (txtNombre.getText().length() != 0 && txtMarca.getText().length() != 0 && txtPrecioC.getText().length() != 0 && txtPrecioV.getText().length() != 0) {

                this.prod = new Producto(this.codigoB, txtNombre.getText(), txtMarca.getText(), cmbTipo.getSelectedItem().toString(), Double.parseDouble(txtPrecioC.getText()), Double.parseDouble(txtPrecioV.getText()));
                this.prod.setCantidad(Integer.parseInt(txtCantidad.getText()));
                if (radStock_si.isSelected()) {
                    this.prod.setStockMin(Integer.parseInt(stockMin.getText()));
                }
                if (vReg != null) {
                    this.prod.setIdPedido(vReg.getPedido().getId());
                    vReg.addProducto(this.prod);
                    vReg.actualizarTabla();
                    dispose();
                    vReg.setTxtCodigoB("");
                    vReg.setVisible(true);
                } else {
                    this.prod.setCodigoBarras(txtCodigo.getText());
                    Almacen a = new Almacen();
                    if(a.agregarProd(this.prod)){
                        JOptionPane.showOptionDialog(this, "Producto agregado", "Aviso", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "}, "OK");
                    }else{
                        JOptionPane.showOptionDialog(this, "Producto no agregado", "Error", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "}, "OK");
                    }
                    dispose();
                }
            } else {
                JOptionPane.showOptionDialog(this, "Datos no válidos", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "}, "OK");
            }
        } else {
            JOptionPane.showOptionDialog(this, "Campos vacíos", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "}, "OK");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton radStock_no;
    private javax.swing.JRadioButton radStock_si;
    private javax.swing.JTextField stockMin;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioC;
    private javax.swing.JTextField txtPrecioV;
    // End of variables declaration//GEN-END:variables
}
