/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Cliente;
import Controller.Secretaria;
import Controller.Utilidades;
import Controller.Venta;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
/**
 *
 * @author lenovo
 */
public class DialogoDevolucion extends javax.swing.JDialog {
  Venta v;
    TableModel modelo;
    TableModel modelo2;
    String idCompra;
    Cliente cliente;
    /**
     * Creates new form DialogoDevolucion
     */
    public DialogoDevolucion(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents(); v = new Venta();
        modelo = v.creaModeloCompras(v.buscarVporCliente(cliente.getNombre(), "DESC"));
        tablaCompras.setModel(modelo);
        personalizaTabla();
        this.cliente = cliente;
    }
    
    private void personalizaTabla(){
         // modificar ancho de columnas de acuerdo al contenido
        tablaCompras.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
         for (int i = 0; i < tablaCompras.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) tablaCompras.getColumnModel();
            TableColumn col = colModel.getColumn(i);           
            switch (i){
                case 0 :  col.setPreferredWidth(0); break;
                case 1 :  col.setPreferredWidth(100); break;
                case 2 :  col.setPreferredWidth(100); break;
                case 3 :  col.setPreferredWidth(513); break;
                case 4 :  col.setPreferredWidth(150); break;
                
            }                       
        }
        
        tablaCompras.setRowHeight(60);
        
        tablaCompras.getColumn(tablaCompras.getColumnName(0)).setHeaderValue(" ");
        tablaCompras.getColumn(tablaCompras.getColumnName(1)).setHeaderValue("Fecha");
        tablaCompras.getColumn(tablaCompras.getColumnName(2)).setHeaderValue("Vendedor");
        tablaCompras.getColumn(tablaCompras.getColumnName(3)).setHeaderValue("Descripción");
        tablaCompras.getColumn(tablaCompras.getColumnName(4)).setHeaderValue("Total");     
        
        tablaCompras.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaCompras.getColumnModel().getColumn(0).setMinWidth(0);
        tablaCompras.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
     
      private void personalizaTablaProd(){
         // modificar ancho de columnas de acuerdo al contenido
        tablaProductos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < tablaProductos.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) tablaProductos.getColumnModel();
            TableColumn col = colModel.getColumn(i);           
            switch (i){
                case 0 :  col.setPreferredWidth(150); break;
                case 1 :  col.setPreferredWidth(475); break;
                case 2 :  col.setPreferredWidth(100); break;
                case 3 :  col.setPreferredWidth(150); break;
                
            }                       
        }
        
        tablaProductos.setRowHeight(20);
        
        tablaProductos.getColumn(tablaProductos.getColumnName(0)).setHeaderValue("");
        tablaProductos.getColumn(tablaProductos.getColumnName(1)).setHeaderValue("Código");
        tablaProductos.getColumn(tablaProductos.getColumnName(2)).setHeaderValue("Descripción");
        tablaProductos.getColumn(tablaProductos.getColumnName(3)).setHeaderValue("Cantidad");
        tablaProductos.getColumn(tablaProductos.getColumnName(4)).setHeaderValue("Precio de Venta");
        
        
        tablaProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProductos.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(0);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        btnRevisar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Compras:");

        jLabel2.setText("Productos:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Tipo", "Precio de Venta"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Vendedor", "Descripción", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaCompras);

        btnRevisar.setText("Ok");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        if(tablaCompras.getSelectedRow() != -1){

            Integer fila = tablaCompras.getSelectedRow();
            Venta comp = new Venta(tablaCompras.getValueAt(fila, 0).toString());
            this.idCompra = tablaCompras.getValueAt(fila, 0).toString();
            modelo2 = comp.creaModProds(comp.obtenerProd(tablaCompras.getValueAt(fila, 0).toString()));
            tablaProductos.setModel(modelo2);
            personalizaTablaProd();
        }
        else{
            JOptionPane.showOptionDialog(this, "Seleccione una compra", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
        }
    }//GEN-LAST:event_btnRevisarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(tablaProductos.getSelectedRow() != -1){
            Integer fila = tablaProductos.getSelectedRow();
            Venta comp = new Venta(this.idCompra);
            if(comp.regDevolucion(this.cliente, tablaProductos.getValueAt(fila, 0).toString(), tablaProductos.getValueAt(fila, 1).toString(),tablaProductos.getValueAt(fila, 4).toString(),tablaProductos.getValueAt(fila, 5).toString(), this.idCompra)){
                JOptionPane.showOptionDialog(this, "Devolución registrada", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
                dispose();
            }else{
                JOptionPane.showOptionDialog(this, "Falló la devolución", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
        else{
            JOptionPane.showOptionDialog(this, "Seleccione un producto", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
