/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author toshiba
 */
public class DialogoCarga extends javax.swing.JDialog {

    /**
     * Creates new form DialogoCarga
     */
    public DialogoCarga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        barraP.setIndeterminate(true);
        barraP.setString("Cargando información");
        monitor(parent);

    }

    private void monitor(final java.awt.Frame parent) {
        final Thread t;
        t = new Thread(new Runnable() {
            Boolean bandera = true;

            @Override
            public void run() {
                DialogoMandoFinanciero dialog = new DialogoMandoFinanciero(parent, false);
                dialog.pack();
                dialog.setVisible(false);
                dialog.setResizable(true);
                dialog.setLocationRelativeTo(null);
               

                while (bandera) {
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                    }
                    if (dialog.getDone()) {
                        bandera = false;
                        setCursor(null); //turn off the wait cursor
                        barraP.setIndeterminate(false);

                        //Permite mostrar el valor del progreso
                        barraP.setStringPainted(true);
                        int x = 1;
                        //Utilizamos un while para emular el valor mínimo y máximo
                        //En este caso 0 - 100
                        while (x <= 100) {
                            barraP.setValue(x);
                            txtCarga.setText("Progreso " + x + "%...\n");
                            //Se incrementa el valor de x
                            x++;
                        }
                        dispose();
                        dialog.setVisible(true);
                        dialog.setEnabled(true);
                        dialog.toFront();
                        dialog.requestFocus();
                    }
                }
            }

        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraP = new javax.swing.JProgressBar();
        txtCarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCarga.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCarga.setText("Cargando . . .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraP, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtCarga)
                .addGap(18, 18, 18)
                .addComponent(barraP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraP;
    private javax.swing.JLabel txtCarga;
    // End of variables declaration//GEN-END:variables
}
