/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Vendedor;
import Controller.Venta;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class DialogoHistorialVentas extends javax.swing.JDialog {

    private TableModel modelo;
    private Venta v;

    /**
     * Creates new form DialogoHistorialVentas
     */
    public DialogoHistorialVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        v = new Venta();
        Vendedor vend = new Vendedor();
        List<Venta> vts = v.obtenerVentas();
        System.out.println("tamaño" + vts.size());
        modelo = v.creaModeloHventas(vts);
        tablaHventas.setModel(modelo);
        personalizaTabla();
        llenarCmbVend(vend.obtenerVendedores());
        txtBuscar.requestFocus();
        chkCliente.setSelected(true);
    }

    private void llenarCmbVend(List<Vendedor> vendedores) {
        String[] cadena = new String[vendedores.size() + 1];
        int i = 1;
        cadena[0] = "Todos";
        for (Vendedor v : vendedores) {
            cadena[i] = v.getNombre();
            i++;
        }
        cmbVend.setModel(new DefaultComboBoxModel((Object[]) cadena));
    }

    private void personalizaTabla() {
        // modificar ancho de columnas de acuerdo al contenido
        tablaHventas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < tablaHventas.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) tablaHventas.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < tablaHventas.getRowCount(); r++) {
                renderer = tablaHventas.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(tablaHventas, tablaHventas.getValueAt(r, i), false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }
            if (i == 3) {
                col.setPreferredWidth(355);
            } else {
                col.setPreferredWidth(width + 20);
            }
        }

        tablaHventas.setRowHeight(60);

        tablaHventas.getColumn(tablaHventas.getColumnName(0)).setHeaderValue(" ");
        tablaHventas.getColumn(tablaHventas.getColumnName(1)).setHeaderValue("Fecha");
        tablaHventas.getColumn(tablaHventas.getColumnName(2)).setHeaderValue("Cliente");
        tablaHventas.getColumn(tablaHventas.getColumnName(3)).setHeaderValue("Descripción");
        tablaHventas.getColumn(tablaHventas.getColumnName(4)).setHeaderValue("Vendedor");
        tablaHventas.getColumn(tablaHventas.getColumnName(5)).setHeaderValue("Total");
        tablaHventas.getColumn(tablaHventas.getColumnName(6)).setHeaderValue("Utilidad");

        tablaHventas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaHventas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaHventas.getColumnModel().getColumn(0).setPreferredWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        chkCliente = new javax.swing.JRadioButton();
        chkCodProd = new javax.swing.JRadioButton();
        chkNomProd = new javax.swing.JRadioButton();
        cmbVend = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarTodo = new javax.swing.JButton();
        cmbOrden = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHventas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        chkCliente.setText("Cliente");
        chkCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkClienteActionPerformed(evt);
            }
        });

        chkCodProd.setText("Código de producto");
        chkCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCodProdActionPerformed(evt);
            }
        });

        chkNomProd.setText("Nombre de producto");
        chkNomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNomProdActionPerformed(evt);
            }
        });

        cmbVend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Alma", "Isaac" }));

        jLabel1.setText("Vendedor:");

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASC", "DESC" }));
        cmbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenActionPerformed(evt);
            }
        });

        jLabel2.setText("Orden:");

        tablaHventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cliente", "Descripción", "Vendedor", "Total", "Utilidad"
            }
        ));
        jScrollPane1.setViewportView(tablaHventas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarTodo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkCliente)
                                .addGap(120, 120, 120)
                                .addComponent(chkNomProd))
                            .addComponent(chkCodProd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(0, 22, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkCliente)
                            .addComponent(chkNomProd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCodProd)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTodo)
                    .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Venta v;
            if (chkCliente.isSelected()) {
                if (cmbVend.getSelectedIndex() == 0) {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCliente(txtBuscar.getText(), cmbOrden.getSelectedItem().toString())); //por cliente
                } else {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCliente(txtBuscar.getText(), cmbVend.getSelectedItem().toString(), cmbOrden.getSelectedItem().toString())); //por cliente y vendedor
                }

            } else if (chkNomProd.isSelected()) {
                if (cmbVend.getSelectedIndex() == 0) {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporNomProd(txtBuscar.getText(), cmbOrden.getSelectedItem().toString())); //por nombre prod
                } else {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporNomProd(txtBuscar.getText(), cmbVend.getSelectedItem().toString(), cmbOrden.getSelectedItem().toString())); //por nombre prod y vendedor
                }

            } else if (chkCodProd.isSelected()) {
                if (cmbVend.getSelectedIndex() == 0) {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCodProd(txtBuscar.getText(), cmbOrden.getSelectedItem().toString())); //por codigo prod
                } else {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCodProd(txtBuscar.getText(), cmbVend.getSelectedItem().toString(), cmbOrden.getSelectedItem().toString())); //por codigo prod y vendedor
                }

            }
            tablaHventas.setModel(modelo);
            personalizaTabla();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Venta v;
        if (Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-, ,]{1,50})$", txtBuscar.getText())) {
            if (chkCliente.isSelected()) {
                if (cmbVend.getSelectedIndex() == 0) {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCliente(txtBuscar.getText(), cmbOrden.getSelectedItem().toString())); //por cliente
                } else {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCliente(txtBuscar.getText(), cmbVend.getSelectedItem().toString(), cmbOrden.getSelectedItem().toString())); //por cliente y vendedor
                }

            } else if (chkNomProd.isSelected()) {
                if (cmbVend.getSelectedIndex() == 0) {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporNomProd(txtBuscar.getText(), cmbOrden.getSelectedItem().toString())); //por nombre prod
                } else {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporNomProd(txtBuscar.getText(), cmbVend.getSelectedItem().toString(), cmbOrden.getSelectedItem().toString())); //por nombre prod y vendedor
                }

            } else if (chkCodProd.isSelected()) {
                if (cmbVend.getSelectedIndex() == 0) {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCodProd(txtBuscar.getText(), cmbOrden.getSelectedItem().toString())); //por codigo prod
                } else {
                    v = new Venta();
                    modelo = v.creaModeloHventas(v.buscarVporCodProd(txtBuscar.getText(), cmbVend.getSelectedItem().toString(), cmbOrden.getSelectedItem().toString())); //por codigo prod y vendedor
                }

            }
            tablaHventas.setModel(modelo);
            personalizaTabla();
        } else {
            JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "}, "OK");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chkClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkClienteActionPerformed
        chkNomProd.setSelected(false);
        chkCodProd.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chkClienteActionPerformed

    private void chkCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCodProdActionPerformed
        chkCliente.setSelected(false);
        chkNomProd.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chkCodProdActionPerformed

    private void chkNomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNomProdActionPerformed
        chkCliente.setSelected(false);
        chkCodProd.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chkNomProdActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        modelo = v.creaModeloHventas(v.obtenerVentas());
        tablaHventas.setModel(modelo);
        personalizaTabla();
        txtBuscar.requestFocus();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoHistorialVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoHistorialVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoHistorialVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoHistorialVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoHistorialVentas dialog = new DialogoHistorialVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JRadioButton chkCliente;
    private javax.swing.JRadioButton chkCodProd;
    private javax.swing.JRadioButton chkNomProd;
    private javax.swing.JComboBox cmbOrden;
    private javax.swing.JComboBox cmbVend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHventas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
