/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.regex.Pattern;
import Controller.Almacen;
import Controller.Pedido;
import Controller.Proveedor;
import Controller.Secretaria;
import Controller.Utilidades;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;
/**
 *
 * @author toshiba
 */
public class IntInventario extends javax.swing.JPanel {
   private TableModel modeloTabla;
    private Proveedor prov;
    /**
     * Creates new form IntInventario
     */
    public IntInventario() {
        initComponents();
         Almacen a = new Almacen();
        modeloTabla = a.obtenerTablaProductos();
        tablaProd.setModel(modeloTabla);
        titulosTabla();
        Pedido p = new Pedido();
        llenarCmbPed(p.obtenerPedidos());
        chNombre.setSelected(true);    
        txtBuscar.requestFocus();
        tablaProd.setOpaque(false);
        this.prov = new Proveedor();
        this.prov.obtenerProveedores();
        llenarCmbProv(this.prov.getProv());
    }
 private void llenarCmbProv(List<Proveedor> proveedores){
       String[] cadena = new String[proveedores.size()+1];
        int i=1;
        cadena[0] = "Todos";
        for(Proveedor p : proveedores){
           cadena[i]=p.getRazonSocial();
            i++;
        }
        cmbProv.setModel(new DefaultComboBoxModel((Object[]) cadena));
    }
        
    
      private void llenarCmbPed(List<Pedido> pedidos){
       String[] cadena = new String[pedidos.size()+1];
        int i=1;
        cadena[0] = "todo";
        for(Pedido p : pedidos){
           cadena[i]=p.getId().toString();
            i++;
        }
        cmbPedido.setModel(new DefaultComboBoxModel((Object[]) cadena));
    }
    
    private void titulosTabla(){
        tablaProd.getColumn(tablaProd.getColumnName(0)).setHeaderValue(" ");
        tablaProd.getColumn(tablaProd.getColumnName(1)).setHeaderValue("Nombre");
        tablaProd.getColumn(tablaProd.getColumnName(2)).setHeaderValue("Marca");
        tablaProd.getColumn(tablaProd.getColumnName(3)).setHeaderValue("Tipo");
        tablaProd.getColumn(tablaProd.getColumnName(4)).setHeaderValue("Cantidad");
        tablaProd.getColumn(tablaProd.getColumnName(5)).setHeaderValue("Precio C");
        tablaProd.getColumn(tablaProd.getColumnName(6)).setHeaderValue("Precio V");
        tablaProd.getColumn(tablaProd.getColumnName(7)).setHeaderValue("Pedido");
        
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaProd.setRowHeight(30);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        chNombre = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbPedido = new javax.swing.JComboBox();
        chCodigo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarTodo = new javax.swing.JButton();
        cmbProv = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        cmbPedido1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(764, 457));
        setMinimumSize(new java.awt.Dimension(764, 457));
        setPreferredSize(new java.awt.Dimension(764, 457));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 190, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        chNombre.setText("Nombre");
        chNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNombreActionPerformed(evt);
            }
        });
        add(chNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel2.setText("Pedido:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        cmbPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPedidoActionPerformed(evt);
            }
        });
        add(cmbPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 80, -1));

        chCodigo.setText("Código");
        chCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCodigoActionPerformed(evt);
            }
        });
        add(chCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel1.setText("Proveedor:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        add(btnMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 100, -1));

        cmbProv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvActionPerformed(evt);
            }
        });
        add(cmbProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 80, -1));

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Marca", "Tipo", "Cantidad", "Precio C", "Precio V", "Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProd.setPreferredSize(new java.awt.Dimension(700, 200));
        jScrollPane1.setViewportView(tablaProd);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 730, 260));

        cmbPedido1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPedido1ActionPerformed(evt);
            }
        });
        add(cmbPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, -1));

        jLabel3.setText("Tipo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jButton1.setText("Dar de baja producto");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 150, -1));

        jButton2.setText(">Excel");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jButton3.setText("PDF");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(chCodigo.isSelected()){
                if(Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-]{1,50})$",txtBuscar.getText())){
                    Almacen a = new Almacen();
                    a.buscarPorCodigoB(txtBuscar.getText());
                    this.modeloTabla = a.creaModeloProdA(a.getProductos().size());
                    tablaProd.setModel(modeloTabla);
                    titulosTabla();
                }else{
                    JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
                }

            }else if(chNombre.isSelected()){
                if(Pattern.matches("^(([A-Z,Ñ,ñ,a-z,-]{1,30})([ ]{0,1})*){1,6}$",txtBuscar.getText())){
                    Almacen a = new Almacen();
                    a.buscarPorNombre(txtBuscar.getText());
                    this.modeloTabla = a.creaModeloProdA(a.getProductos().size());
                    tablaProd.setModel(modeloTabla);
                    titulosTabla();
                }else{
                    JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
                }
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(chCodigo.isSelected()){
            if(Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-]{1,50})$",txtBuscar.getText())){
                Almacen a = new Almacen();
                a.buscarPorCodigoB(txtBuscar.getText());
                this.modeloTabla = a.creaModeloProdA(a.getProductos().size());
                tablaProd.setModel(modeloTabla);
                titulosTabla();
            }else{
                JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }

        }else if(chNombre.isSelected()){
            if(Pattern.matches("^(([A-Z,Ñ,ñ,a-z,-]{1,30})([ ]{0,1})*){1,6}$",txtBuscar.getText())){
                Almacen a = new Almacen();
                a.buscarPorNombre(txtBuscar.getText());
                this.modeloTabla = a.creaModeloProdA(a.getProductos().size());
                tablaProd.setModel(modeloTabla);
                titulosTabla();
            }else{
                JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNombreActionPerformed
        chCodigo.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chNombreActionPerformed

    private void cmbPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPedidoActionPerformed
        Pedido p = new Pedido();
        System.out.println(cmbPedido.getSelectedIndex());
        if(cmbPedido.getSelectedIndex() == 0){
            Almacen a = new Almacen();
            modeloTabla = a.obtenerTablaProductos();
            tablaProd.setModel(modeloTabla);
            titulosTabla();
        }else{
            String id = p.obtenerPedidos().get(cmbPedido.getSelectedIndex()-1).getId().toString();
            Almacen a = new Almacen();
            a.buscarPorPedido(id);
            modeloTabla = a.creaModeloProdA(a.getProductos().size());
            tablaProd.setModel(modeloTabla);
            titulosTabla();
        }
    }//GEN-LAST:event_cmbPedidoActionPerformed

    private void chCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCodigoActionPerformed
        chNombre.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chCodigoActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        Almacen a = new Almacen();
        modeloTabla = a.obtenerTablaProductos();
        tablaProd.setModel(modeloTabla);
        titulosTabla();
        txtBuscar.setText("");
        cmbPedido.setSelectedIndex(0);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void cmbProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvActionPerformed
        if(cmbProv.getSelectedIndex()!=0){
            Almacen a = new Almacen();
            a.buscarPorProv(cmbProv.getSelectedItem().toString());
            modeloTabla = a.creaModeloProdA(a.getProductos().size());
            tablaProd.setModel(modeloTabla);
            titulosTabla();
        }
    }//GEN-LAST:event_cmbProvActionPerformed

    private void cmbPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPedido1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JRadioButton chCodigo;
    private javax.swing.JRadioButton chNombre;
    private javax.swing.JComboBox cmbPedido;
    private javax.swing.JComboBox cmbPedido1;
    private javax.swing.JComboBox cmbProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
