/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Productos;
import Controller.Secretaria;
import Controller.Utilidades;
import java.awt.event.KeyEvent;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class IntProductos extends javax.swing.JFrame {
    TableModel modeloTabla;
    /**
     * Creates new form IntProductos
     */
    public IntProductos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/29.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(fal­se); 
        Productos prods = new Productos();
        modeloTabla = prods.obtenerTablaProductos();
        tablaProd.setModel(modeloTabla);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
        titulosTabla();
        chNombre.setSelected(true); 
        
    }
    
       private void titulosTabla(){
        tablaProd.getColumn(tablaProd.getColumnName(0)).setHeaderValue("Código Barras");
        tablaProd.getColumn(tablaProd.getColumnName(1)).setHeaderValue("Nombre");
        tablaProd.getColumn(tablaProd.getColumnName(2)).setHeaderValue("Marca");
        tablaProd.getColumn(tablaProd.getColumnName(3)).setHeaderValue("Tipo");
        tablaProd.getColumn(tablaProd.getColumnName(4)).setHeaderValue("Precio de Venta");
        tablaProd.getColumn(tablaProd.getColumnName(5)).setHeaderValue("Precio de Compra");
        tablaProd.getColumn(tablaProd.getColumnName(6)).setHeaderValue("# Ventas");
        tablaProd.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        chCodigo = new javax.swing.JRadioButton();
        chNombre = new javax.swing.JRadioButton();
        btnAgregaProd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAlmacen = new javax.swing.JMenu();
        sMnuGestProd = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        sMnuAgregarCl = new javax.swing.JMenuItem();
        sMnuRegVen = new javax.swing.JMenuItem();
        sMnuGestionarCl = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenu();
        sMnuRegPed = new javax.swing.JMenuItem();
        sMnuAgregarProv = new javax.swing.JMenuItem();
        sMnuGestionarProv = new javax.swing.JMenuItem();
        mnuVendedores = new javax.swing.JMenu();
        sMnuAgVend = new javax.swing.JMenuItem();
        sMnuGestVend = new javax.swing.JMenuItem();
        mnuContabilidad = new javax.swing.JMenu();
        sMnuAgregarCta = new javax.swing.JMenuItem();
        sMnuEdoRes = new javax.swing.JMenuItem();
        sMnuFinanzas = new javax.swing.JMenuItem();
        mnuPeriodo = new javax.swing.JMenu();
        smnuBalGen = new javax.swing.JMenuItem();
        sMnuCerrPeriodo = new javax.swing.JMenuItem();
        mnuOpciones1 = new javax.swing.JMenu();
        smnuBalGen1 = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar productos");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Tipo", "Precio de venta", "Precio Compra", "# ventas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProd);

        btnActualizar.setText("Actualizar datos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        chCodigo.setText("Código");
        chCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCodigoActionPerformed(evt);
            }
        });

        chNombre.setText("Nombre");
        chNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNombreActionPerformed(evt);
            }
        });

        btnAgregaProd.setText("Agregar Producto");
        btnAgregaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaProdActionPerformed(evt);
            }
        });

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 0, 5, 20));

        mnuAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/almacen1.png"))); // NOI18N
        mnuAlmacen.setText("Almacen");
        mnuAlmacen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuAlmacen.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuGestProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuGestProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestProd.setText("Inventario");
        sMnuGestProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestProdActionPerformed(evt);
            }
        });
        mnuAlmacen.add(sMnuGestProd);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Estadísticas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuAlmacen.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Administrar productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAlmacen.add(jMenuItem1);

        jMenuBar1.add(mnuAlmacen);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        mnuClientes.setText("Clientes");
        mnuClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuClientes.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarCl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuAgregarCl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarCl.setText("Agregar Cliente");
        sMnuAgregarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarClActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuAgregarCl);

        sMnuRegVen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        sMnuRegVen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuRegVen.setText("Historial de ventas");
        sMnuRegVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuRegVenActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuRegVen);

        sMnuGestionarCl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        sMnuGestionarCl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestionarCl.setText("Operaciones");
        sMnuGestionarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestionarClActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuGestionarCl);

        jMenuBar1.add(mnuClientes);

        mnuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N
        mnuProveedores.setText("Proveedores");
        mnuProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuProveedores.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuRegPed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        sMnuRegPed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuRegPed.setText("Registrar Pedido");
        sMnuRegPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuRegPedActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuRegPed);

        sMnuAgregarProv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarProv.setText("Agregar Proveedor");
        sMnuAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarProvActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuAgregarProv);

        sMnuGestionarProv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        sMnuGestionarProv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestionarProv.setText("Administrar Proveedores");
        sMnuGestionarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestionarProvActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuGestionarProv);

        jMenuBar1.add(mnuProveedores);

        mnuVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedores.png"))); // NOI18N
        mnuVendedores.setText("Empleados");
        mnuVendedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuVendedores.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgVend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgVend.setText("Agregar vendedor");
        sMnuAgVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgVendActionPerformed(evt);
            }
        });
        mnuVendedores.add(sMnuAgVend);

        sMnuGestVend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        sMnuGestVend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestVend.setText("Administrar vendedores");
        sMnuGestVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestVendActionPerformed(evt);
            }
        });
        mnuVendedores.add(sMnuGestVend);

        jMenuBar1.add(mnuVendedores);

        mnuContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contabilidad.png"))); // NOI18N
        mnuContabilidad.setText("Contabilidad");
        mnuContabilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuContabilidad.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarCta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarCta.setText("Agregar cuenta");
        sMnuAgregarCta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarCtaActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuAgregarCta);

        sMnuEdoRes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        sMnuEdoRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuEdoRes.setText("Estado de Resultados");
        sMnuEdoRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuEdoResActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuEdoRes);

        sMnuFinanzas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        sMnuFinanzas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuFinanzas.setText("Mando financiero");
        sMnuFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuFinanzasActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuFinanzas);

        jMenuBar1.add(mnuContabilidad);

        mnuPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estadisticas.png"))); // NOI18N
        mnuPeriodo.setText("Periodos");
        mnuPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuPeriodo.setMargin(new java.awt.Insets(0, 0, 0, 10));

        smnuBalGen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        smnuBalGen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smnuBalGen.setText("Histórico");
        smnuBalGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuBalGenActionPerformed(evt);
            }
        });
        mnuPeriodo.add(smnuBalGen);

        sMnuCerrPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuCerrPeriodo.setText("Cerrar periodo");
        sMnuCerrPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuCerrPeriodoActionPerformed(evt);
            }
        });
        mnuPeriodo.add(sMnuCerrPeriodo);

        jMenuBar1.add(mnuPeriodo);

        mnuOpciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajustes.png"))); // NOI18N
        mnuOpciones1.setText("Opciones");
        mnuOpciones1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuOpciones1.setMargin(new java.awt.Insets(0, 0, 0, 10));

        smnuBalGen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smnuBalGen1.setText("Almacen");
        smnuBalGen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuBalGen1ActionPerformed(evt);
            }
        });
        mnuOpciones1.add(smnuBalGen1);

        jMenuBar1.add(mnuOpciones1);

        mnuOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encender-esquema-semicirculo_318-34691.png"))); // NOI18N
        mnuOpciones.setText("Salir");
        mnuOpciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnuOpciones.setMargin(new java.awt.Insets(0, 0, 0, 10));
        mnuOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOpcionesMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregaProd)
                        .addGap(47, 47, 47)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chNombre)
                        .addGap(18, 18, 18)
                        .addComponent(chCodigo)
                        .addGap(119, 119, 119)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnBuscar)
                        .addGap(94, 94, 94)
                        .addComponent(btnMostrarTodo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarTodo)
                            .addComponent(btnBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chCodigo)
                            .addComponent(chNombre))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnAgregaProd))
                .addGap(63, 63, 63))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarDatos(){
        Productos prods = new Productos();
        modeloTabla = prods.obtenerTablaProductos();
        tablaProd.setModel(modeloTabla);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
        titulosTabla();
    }
    
    private void tablaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaProdMouseClicked

    private void sMnuGestProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestProdActionPerformed
        IntAlmacen v = new IntAlmacen();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestProdActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IntProductos v = new IntProductos();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sMnuAgregarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarClActionPerformed
        IntAgregarCl v = new IntAgregarCl();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarClActionPerformed

    private void sMnuRegVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuRegVenActionPerformed
        IntHistoVenta v = new IntHistoVenta();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuRegVenActionPerformed

    private void sMnuGestionarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestionarClActionPerformed
        IntClientes v = new IntClientes();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestionarClActionPerformed

    private void sMnuRegPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuRegPedActionPerformed
        IntSelectProv v = new IntSelectProv();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuRegPedActionPerformed

    private void sMnuAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarProvActionPerformed
        IntAgregarProv v = new IntAgregarProv();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarProvActionPerformed

    private void sMnuGestionarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestionarProvActionPerformed
        IntProveedores v = new IntProveedores();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestionarProvActionPerformed

    private void sMnuAgVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgVendActionPerformed
        IntAgregarVend v = new IntAgregarVend();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgVendActionPerformed

    private void sMnuGestVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestVendActionPerformed
        IntVendedores v = new IntVendedores();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestVendActionPerformed

    private void sMnuAgregarCtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarCtaActionPerformed
        IntAgregarCta v = new IntAgregarCta();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarCtaActionPerformed

    private void sMnuEdoResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuEdoResActionPerformed
        IntEdoRes edo = new IntEdoRes();
        edo.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuEdoResActionPerformed

    private void sMnuFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuFinanzasActionPerformed
        IntCarga c = new IntCarga();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuFinanzasActionPerformed

    private void smnuBalGen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuBalGen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smnuBalGen1ActionPerformed

    private void smnuBalGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuBalGenActionPerformed
        IntBalanceGral bg = new IntBalanceGral();
        bg.setVisible(true);
        dispose();
    }//GEN-LAST:event_smnuBalGenActionPerformed

    private void sMnuCerrPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuCerrPeriodoActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(
            this, "¿Lo confirmas?");
        if (JOptionPane.OK_OPTION == confirmado){
            Utilidades uts = new Utilidades();
            String fecha = uts.obtFechaStringDMA();
            Secretaria mary = new Secretaria();

            if(mary.cierraPeriodo(fecha)){
                JOptionPane.showOptionDialog(this, "Periodo cerrado exitosamente", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
                IntCuentas c = new IntCuentas();
                c.setVisible(true);
                dispose();
            }else{
                JOptionPane.showOptionDialog(this, "Error al cerrar periodo", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
    }//GEN-LAST:event_sMnuCerrPeriodoActionPerformed

    private void mnuOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOpcionesMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuOpcionesMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(this.tablaProd.getSelectedRow() != -1){
            String codigo = tablaProd.getValueAt(tablaProd.getSelectedRow(), 0).toString();
            //IntModProd v = new IntModProd(this,codigo);
          //  v.setVisible(true);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void chNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNombreActionPerformed
        chCodigo.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chNombreActionPerformed

    private void chCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCodigoActionPerformed
        chNombre.setSelected(false);
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chCodigoActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(chCodigo.isSelected()){
                if(Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-]{1,50})$",txtBuscar.getText())){
                    Productos a = new Productos();
                    a.buscarPorCodigoB(txtBuscar.getText());
                    this.modeloTabla = a.creaModelo(a.getProductos().size());
                    tablaProd.setModel(modeloTabla);
                    titulosTabla();
                }else{
                    JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
                }

            }else if(chNombre.isSelected()){
                if(Pattern.matches("^(([A-Z,Ñ,ñ,a-z,-]{1,30})([ ]{0,1})*){1,6}$",txtBuscar.getText())){
                    Productos a = new Productos();
                    a.buscarPorNombre(txtBuscar.getText());
                    this.modeloTabla = a.creaModelo(a.getProductos().size());
                    tablaProd.setModel(modeloTabla);
                    titulosTabla();
                }else{
                    JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
                }
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(chCodigo.isSelected()){
            if(Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-]{1,50})$",txtBuscar.getText())){
                Productos a = new Productos();
                a.buscarPorCodigoB(txtBuscar.getText());
                this.modeloTabla = a.creaModelo(a.getProductos().size());
                tablaProd.setModel(modeloTabla);
                titulosTabla();
            }else{
                JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }

        }else if(chNombre.isSelected()){
            if(Pattern.matches("^(([A-Z,Ñ,ñ,a-z,-]{1,30})([ ]{0,1})*){1,6}$",txtBuscar.getText())){
                Productos a = new Productos();
                a.buscarPorNombre(txtBuscar.getText());
                this.modeloTabla = a.creaModelo(a.getProductos().size());
                tablaProd.setModel(modeloTabla);
                titulosTabla();
            }else{
                JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        Productos prods = new Productos();
        modeloTabla = prods.obtenerTablaProductos();
        tablaProd.setModel(modeloTabla);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
        titulosTabla();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnAgregaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaProdActionPerformed
        IntAgregarProd ag = new IntAgregarProd();
        ag.setVisible(true);
    }//GEN-LAST:event_btnAgregaProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregaProd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JRadioButton chCodigo;
    private javax.swing.JRadioButton chNombre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuAlmacen;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuContabilidad;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuOpciones1;
    private javax.swing.JMenu mnuPeriodo;
    private javax.swing.JMenu mnuProveedores;
    private javax.swing.JMenu mnuVendedores;
    private javax.swing.JMenuItem sMnuAgVend;
    private javax.swing.JMenuItem sMnuAgregarCl;
    private javax.swing.JMenuItem sMnuAgregarCta;
    private javax.swing.JMenuItem sMnuAgregarProv;
    private javax.swing.JMenuItem sMnuCerrPeriodo;
    private javax.swing.JMenuItem sMnuEdoRes;
    private javax.swing.JMenuItem sMnuFinanzas;
    private javax.swing.JMenuItem sMnuGestProd;
    private javax.swing.JMenuItem sMnuGestVend;
    private javax.swing.JMenuItem sMnuGestionarCl;
    private javax.swing.JMenuItem sMnuGestionarProv;
    private javax.swing.JMenuItem sMnuRegPed;
    private javax.swing.JMenuItem sMnuRegVen;
    private javax.swing.JMenuItem smnuBalGen;
    private javax.swing.JMenuItem smnuBalGen1;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
