/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Almacen;
import Controller.Cliente;
import Controller.Producto;
import Controller.Secretaria;
import Controller.Utilidades;
import Controller.Vendedor;
import Controller.Venta;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class IntVenta extends javax.swing.JFrame {
    private Cliente cliente;
    private TableModel modeloTabla1;
    private TableModel modeloTabla2;
    private Venta v;
    private List <Producto> productos; 
    private Double precioPersonalizado;
    private Vendedor vend;
    /*
     * Creates new form IntVenta
     */

    public void setPrecioPersonalizado(Double precioPersonalizado) {
        this.precioPersonalizado = precioPersonalizado;
    }
    
    
    public IntVenta(String idCliente, Vendedor vendedor) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/29.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(fal­se); 
        cliente = new Cliente(idCliente);
        Almacen a = new Almacen();
        a.obtenerProductos();
        this.productos = a.getProductos();
        modeloTabla1 = a.creaModeloProdV1(productos.size());
        tablaProd.setModel(modeloTabla1);
        titulosTabla();
        v = new Venta();      
        v.setVendedor(vendedor.getNombre());
        this.vend = vendedor;
        chNombre.setSelected(true);
        txtBuscar.requestFocus();
    }
    
    private void titulosTabla(){
        tablaProd.getColumn(tablaProd.getColumnName(0)).setHeaderValue(" ");
        tablaProd.getColumn(tablaProd.getColumnName(1)).setHeaderValue("Nombre");
        tablaProd.getColumn(tablaProd.getColumnName(2)).setHeaderValue("Marca");
        tablaProd.getColumn(tablaProd.getColumnName(3)).setHeaderValue("Tipo");
        tablaProd.getColumn(tablaProd.getColumnName(4)).setHeaderValue("Cantidad");
        tablaProd.getColumn(tablaProd.getColumnName(5)).setHeaderValue("Precio C");
        tablaProd.getColumn(tablaProd.getColumnName(6)).setHeaderValue("Precio V");
         tablaProd.getColumn(tablaProd.getColumnName(7)).setHeaderValue("pedido");
         
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaProd.setRowHeight(40);
       /* 
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(0).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(0).setPreferredWidth(0);*/
    }
    
     private void titulosTabla2(){
        tablaVenta.getColumn(tablaVenta.getColumnName(0)).setHeaderValue(" ");
        tablaVenta.getColumn(tablaVenta.getColumnName(1)).setHeaderValue("Nombre");
        tablaVenta.getColumn(tablaVenta.getColumnName(2)).setHeaderValue("Marca");
        tablaVenta.getColumn(tablaVenta.getColumnName(3)).setHeaderValue("Tipo");
        tablaVenta.getColumn(tablaVenta.getColumnName(4)).setHeaderValue("Cantidad");
        tablaVenta.getColumn(tablaVenta.getColumnName(5)).setHeaderValue("Precio unitario");
        tablaVenta.getColumn(tablaVenta.getColumnName(6)).setHeaderValue("Precio neto");
        tablaVenta.getColumn(tablaVenta.getColumnName(7)).setHeaderValue("Pedido");
         
        tablaVenta.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setMinWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaVenta.setRowHeight(40);

        /*
        tablaVenta.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setMinWidth(0);
        tablaVenta.getColumnModel().getColumn(0).setPreferredWidth(0);*/
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNeto = new javax.swing.JLabel();
        chNombre = new javax.swing.JRadioButton();
        chCodigo = new javax.swing.JRadioButton();
        btnMostrarTodo = new javax.swing.JButton();
        btnCompletar = new javax.swing.JButton();
        btnCompletar1 = new javax.swing.JButton();
        chkPrecio = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAlmacen = new javax.swing.JMenu();
        sMnuGestProd = new javax.swing.JMenuItem();
        sMnuRegPed = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        sMnuAgregarCl = new javax.swing.JMenuItem();
        sMnuRegVen = new javax.swing.JMenuItem();
        sMnuGestionarCl = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenu();
        sMnuAgregarProv = new javax.swing.JMenuItem();
        sMnuGestionarProv = new javax.swing.JMenuItem();
        mnuVendedores = new javax.swing.JMenu();
        sMnuAgVend = new javax.swing.JMenuItem();
        sMnuGestVend = new javax.swing.JMenuItem();
        mnuContabilidad = new javax.swing.JMenu();
        sMnuAgregarCta = new javax.swing.JMenuItem();
        smnuBalGen = new javax.swing.JMenuItem();
        sMnuEdoRes = new javax.swing.JMenuItem();
        sMnuFinanzas = new javax.swing.JMenuItem();
        mnuPeriodo = new javax.swing.JMenu();
        sMnuCerrPeriodo = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        sMnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta");
        setResizable(false);

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Tipo", "Cantidad", "Precio C", "Precio V"
            }
        ));
        jScrollPane1.setViewportView(tablaProd);

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Tipo", "Cantidad", "Precio unitario", "Precio neto"
            }
        ));
        tablaVenta.setToolTipText("");
        jScrollPane2.setViewportView(tablaVenta);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Carrito:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total $");

        lblNeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNeto.setText("0.0");

        chNombre.setText("Nombre");
        chNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNombreActionPerformed(evt);
            }
        });

        chCodigo.setText("Código");
        chCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCodigoActionPerformed(evt);
            }
        });

        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnCompletar.setText("Completar");
        btnCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarActionPerformed(evt);
            }
        });

        btnCompletar1.setText("Cancelar");
        btnCompletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletar1ActionPerformed(evt);
            }
        });

        chkPrecio.setText("cambiar precio");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 0, 5, 20));

        mnuAlmacen.setText("Almacen");
        mnuAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuAlmacen.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuGestProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuGestProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestProd.setText("Existencias");
        sMnuGestProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestProdActionPerformed(evt);
            }
        });
        mnuAlmacen.add(sMnuGestProd);

        sMnuRegPed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        sMnuRegPed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuRegPed.setText("Registrar Pedido");
        sMnuRegPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuRegPedActionPerformed(evt);
            }
        });
        mnuAlmacen.add(sMnuRegPed);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Gestionar productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAlmacen.add(jMenuItem1);

        jMenuBar1.add(mnuAlmacen);

        mnuClientes.setText("Clientes");
        mnuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuClientes.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarCl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuAgregarCl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarCl.setText("Agregar Cliente");
        sMnuAgregarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarClActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuAgregarCl);

        sMnuRegVen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        sMnuRegVen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuRegVen.setText("Historial de ventas");
        sMnuRegVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuRegVenActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuRegVen);

        sMnuGestionarCl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        sMnuGestionarCl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestionarCl.setText("Operaciones");
        sMnuGestionarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestionarClActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuGestionarCl);

        jMenuBar1.add(mnuClientes);

        mnuProveedores.setText("Proveedores");
        mnuProveedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuProveedores.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarProv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarProv.setText("Agregar Proveedor");
        sMnuAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarProvActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuAgregarProv);

        sMnuGestionarProv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        sMnuGestionarProv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestionarProv.setText("Gestionar Proveedores");
        sMnuGestionarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestionarProvActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuGestionarProv);

        jMenuBar1.add(mnuProveedores);

        mnuVendedores.setText("Vendedores");
        mnuVendedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuVendedores.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgVend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgVend.setText("Agregar vendedor");
        sMnuAgVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgVendActionPerformed(evt);
            }
        });
        mnuVendedores.add(sMnuAgVend);

        sMnuGestVend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        sMnuGestVend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestVend.setText("Gestionar vendedores");
        sMnuGestVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestVendActionPerformed(evt);
            }
        });
        mnuVendedores.add(sMnuGestVend);

        jMenuBar1.add(mnuVendedores);

        mnuContabilidad.setText("Contabilidad");
        mnuContabilidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuContabilidad.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarCta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarCta.setText("Agregar cuenta");
        sMnuAgregarCta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarCtaActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuAgregarCta);

        smnuBalGen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        smnuBalGen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smnuBalGen.setText("Balance General");
        smnuBalGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuBalGenActionPerformed(evt);
            }
        });
        mnuContabilidad.add(smnuBalGen);

        sMnuEdoRes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        sMnuEdoRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuEdoRes.setText("Estado de Resultados");
        sMnuEdoRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuEdoResActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuEdoRes);

        sMnuFinanzas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        sMnuFinanzas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuFinanzas.setText("Mando financiero");
        sMnuFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuFinanzasActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuFinanzas);

        jMenuBar1.add(mnuContabilidad);

        mnuPeriodo.setText("Periodos");
        mnuPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuPeriodo.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuCerrPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuCerrPeriodo.setText("Cerrar periodo");
        sMnuCerrPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuCerrPeriodoActionPerformed(evt);
            }
        });
        mnuPeriodo.add(sMnuCerrPeriodo);

        jMenuBar1.add(mnuPeriodo);

        mnuOpciones.setText("Opciones");
        mnuOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuOpciones.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuSalir.setText("Salir");
        sMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuSalirActionPerformed(evt);
            }
        });
        mnuOpciones.add(sMnuSalir);

        jMenuBar1.add(mnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(186, 186, 186)
                        .addComponent(chkPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(lblNeto)
                        .addGap(298, 298, 298)
                        .addComponent(btnCompletar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCompletar1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(chNombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnBuscar)
                        .addGap(184, 184, 184)
                        .addComponent(btnMostrarTodo)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chNombre)
                            .addComponent(chCodigo)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostrarTodo)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkPrecio)
                        .addComponent(jLabel1)
                        .addComponent(btnQuitar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNeto))
                        .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCompletar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNombreActionPerformed
        chCodigo.setSelected(false);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chNombreActionPerformed

    private void chCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCodigoActionPerformed
        chNombre.setSelected(false);
        txtBuscar.setText("");
        txtBuscar.requestFocus();
    }//GEN-LAST:event_chCodigoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(Pattern.matches("^([A-Z,Ñ,ñ,a-z,0-9,-, ,]{1,50})$",txtBuscar.getText())){
                if(chNombre.isSelected()){
            Almacen a = new Almacen();
            a.buscarPorNombre(txtBuscar.getText());
            for(Producto p : a.getProductos()){
                for(Producto p1 : productos){
                    if(p.getId().equals(p1.getId())){
                        p.setCantidad(p1.getCantidad());
                    }
                }
            }
            this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
            tablaProd.setModel(modeloTabla1);
            titulosTabla();
            
        }else if(chCodigo.isSelected()){
            Almacen a = new Almacen();
            a.buscarPorCodigoB(txtBuscar.getText());
            for(Producto p : a.getProductos()){
                for(Producto p1 : productos){
                    if(p.getId().equals(p1.getId())){
                        p.setCantidad(p1.getCantidad());
                    }
                }
            }
            this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
            tablaProd.setModel(modeloTabla1);
            titulosTabla();
            
            
        }else{
             JOptionPane.showOptionDialog(this, "Seleccione una opción", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");         
        }
        
        }else{
            JOptionPane.showOptionDialog(this, "No permitido", "Aviso", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK"); 
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        Almacen a = new Almacen();
        a.setProductos(productos);
        modeloTabla1 = a.creaModeloProdV1(productos.size());
        tablaProd.setModel(modeloTabla1);
        titulosTabla();
        txtBuscar.setText("");
        txtBuscar.requestFocus();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         if(tablaProd.getSelectedRow() != -1){
            Integer fila = tablaProd.getSelectedRow();     
            if(Integer.parseInt(tablaProd.getValueAt(fila, 4).toString()) > 0){
                if(chkPrecio.isSelected()){
                   this.precioPersonalizado = Double.parseDouble(JOptionPane.showInputDialog (this, "Precio de venta: ", "Precio personalizado",JOptionPane.INFORMATION_MESSAGE));    
                   v.agregarAlCarrito(tablaProd.getValueAt(fila, 0).toString(),this.precioPersonalizado);    
                }else{
                   v.agregarAlCarrito(tablaProd.getValueAt(fila, 0).toString());    
                }                                
                modeloTabla2 = v.creaModTblList(v.getListaV().size());                
                tablaVenta.setModel(modeloTabla2);
                titulosTabla2();
                lblNeto.setText(v.getNeto().toString());
              
                for(Producto p1 : productos){
                    if(p1.getId().equals(tablaProd.getValueAt(fila, 0).toString())){
                        p1.setCantidad(p1.getCantidad()-1);
                    }
                }
                Almacen a = new Almacen();
                a.setProductos(productos);
                modeloTabla1 = a.creaModeloProdV1(productos.size());                
                tablaProd.setModel(modeloTabla1);
                titulosTabla();        
                txtBuscar.setText("");
                txtBuscar.requestFocus();
            }else{
                JOptionPane.showOptionDialog(this, "No hay más existencia", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK"); 
            }
    }
        else{
            JOptionPane.showOptionDialog(this, "Seleccione un producto", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK"); 
        }        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
         if(tablaVenta.getSelectedRow() != -1){
            Integer fila = tablaVenta.getSelectedRow();     
            v.quitarDlCarrito(tablaVenta.getValueAt(fila, 0).toString());
            modeloTabla2 = v.creaModTblList(v.getListaV().size());                                            
            lblNeto.setText(v.getNeto().toString());
            for(Producto p1 : productos){
                    if(p1.getId().equals(tablaVenta.getValueAt(fila, 0).toString())){
                        p1.setCantidad(p1.getCantidad()+1);
                    }
                }
                Almacen a = new Almacen();
                a.setProductos(productos);
                modeloTabla1 = a.creaModeloProdV1(productos.size());    
                
                tablaVenta.setModel(modeloTabla2);
                titulosTabla2(); 
                tablaProd.setModel(modeloTabla1);
                titulosTabla();  
        }
        else{
            JOptionPane.showOptionDialog(this, "Seleccione un producto de la venta", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK"); 
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnCompletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletar1ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Desea cancelar la venta ?", "Seleccione una opción", JOptionPane.YES_NO_OPTION) == 0){
            IntClientes c = new IntClientes();
            c.setVisible(true);
            dispose();
        }        
    }//GEN-LAST:event_btnCompletar1ActionPerformed

    private void btnCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarActionPerformed
        v.setCostoVenta(v.getCostoVenta());
        v.setNeto(v.getNeto());
        v.setIdCl(cliente.getId());
        
        if(v.registrarVenta()){ //se registra venta
            Almacen a = new Almacen();
            a.actualizarProducto(this.productos); // se actualizan las cantidades en almacen
            cliente.actualizarSaldo(v.getNeto(),this.cliente,'c'); // se actualiza el saldo del cliente
            vend.actualizaVentas(vend);
            JOptionPane.showOptionDialog(this, "Venta finalizada", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");                     
            IntClientes c = new IntClientes();
            c.setVisible(true);
            dispose();
        }else{
            JOptionPane.showOptionDialog(this, "Agregue productos", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK"); 
        }
    }//GEN-LAST:event_btnCompletarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        if(chNombre.isSelected()){
            Almacen a = new Almacen();
            a.buscarPorNombre(txtBuscar.getText());
            for(Producto p : a.getProductos()){
                for(Producto p1 : productos){
                    if(p.getId().equals(p1.getId())){
                        p.setCantidad(p1.getCantidad());
                    }
                }
            }
            this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
            tablaProd.setModel(modeloTabla1);
            titulosTabla();
            
        }else if(chCodigo.isSelected()){
            Almacen a = new Almacen();
            a.buscarPorCodigoB(txtBuscar.getText());
            for(Producto p : a.getProductos()){
                for(Producto p1 : productos){
                    if(p.getId().equals(p1.getId())){
                        p.setCantidad(p1.getCantidad());
                    }
                }
            }
            this.modeloTabla1 = a.creaModeloProdV1(a.getProductos().size());
            tablaProd.setModel(modeloTabla1);
            titulosTabla();
        }
     }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void sMnuGestProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestProdActionPerformed
        IntAlmacen v = new IntAlmacen();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestProdActionPerformed

    private void sMnuRegPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuRegPedActionPerformed
        IntSelectProv v = new IntSelectProv();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuRegPedActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IntProductos v = new IntProductos();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sMnuAgregarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarClActionPerformed
        IntAgregarCl v = new IntAgregarCl();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarClActionPerformed

    private void sMnuRegVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuRegVenActionPerformed
        IntHistoVenta v = new IntHistoVenta();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuRegVenActionPerformed

    private void sMnuGestionarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestionarClActionPerformed
        IntClientes v = new IntClientes();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestionarClActionPerformed

    private void sMnuAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarProvActionPerformed
        IntAgregarProv v = new IntAgregarProv();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarProvActionPerformed

    private void sMnuGestionarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestionarProvActionPerformed
        IntProveedores v = new IntProveedores();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestionarProvActionPerformed

    private void sMnuAgVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgVendActionPerformed
        IntAgregarVend v = new IntAgregarVend();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgVendActionPerformed

    private void sMnuGestVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestVendActionPerformed
        IntVendedores v = new IntVendedores();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestVendActionPerformed

    private void sMnuAgregarCtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarCtaActionPerformed
        IntAgregarCta v = new IntAgregarCta();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarCtaActionPerformed

    private void smnuBalGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuBalGenActionPerformed
        IntBalanceGral bg = new IntBalanceGral();
        bg.setVisible(true);
        dispose();
    }//GEN-LAST:event_smnuBalGenActionPerformed

    private void sMnuEdoResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuEdoResActionPerformed
        IntEdoRes edo = new IntEdoRes();
        edo.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuEdoResActionPerformed

    private void sMnuFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuFinanzasActionPerformed
        IntCarga c = new IntCarga();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuFinanzasActionPerformed

    private void sMnuCerrPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuCerrPeriodoActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(
            this, "¿Lo confirmas?");
        if (JOptionPane.OK_OPTION == confirmado){
            Utilidades uts = new Utilidades();
            String fecha = uts.obtFechaStringDMA();
            Secretaria mary = new Secretaria();

            if(mary.cierraPeriodo(fecha)){
                JOptionPane.showOptionDialog(this, "Periodo cerrado exitosamente", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
                IntCuentas c = new IntCuentas();
                c.setVisible(true);
                dispose();
            }else{
                JOptionPane.showOptionDialog(this, "Error al cerrar periodo", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
    }//GEN-LAST:event_sMnuCerrPeriodoActionPerformed

    private void sMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_sMnuSalirActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCompletar;
    private javax.swing.JButton btnCompletar1;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JRadioButton chCodigo;
    private javax.swing.JRadioButton chNombre;
    private javax.swing.JRadioButton chkPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNeto;
    private javax.swing.JMenu mnuAlmacen;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuContabilidad;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuPeriodo;
    private javax.swing.JMenu mnuProveedores;
    private javax.swing.JMenu mnuVendedores;
    private javax.swing.JMenuItem sMnuAgVend;
    private javax.swing.JMenuItem sMnuAgregarCl;
    private javax.swing.JMenuItem sMnuAgregarCta;
    private javax.swing.JMenuItem sMnuAgregarProv;
    private javax.swing.JMenuItem sMnuCerrPeriodo;
    private javax.swing.JMenuItem sMnuEdoRes;
    private javax.swing.JMenuItem sMnuFinanzas;
    private javax.swing.JMenuItem sMnuGestProd;
    private javax.swing.JMenuItem sMnuGestVend;
    private javax.swing.JMenuItem sMnuGestionarCl;
    private javax.swing.JMenuItem sMnuGestionarProv;
    private javax.swing.JMenuItem sMnuRegPed;
    private javax.swing.JMenuItem sMnuRegVen;
    private javax.swing.JMenuItem sMnuSalir;
    private javax.swing.JMenuItem smnuBalGen;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
