/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Secretaria;
import Controller.Utilidades;
import Controller.Vendedor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class IntVendedores extends javax.swing.JFrame {
private TableModel modeloTabla ;
    /**
     * Creates new form IntVendeores
     */
    public IntVendedores() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/29.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(fal­se); 
        Vendedor vend = new Vendedor();        
        modeloTabla = vend.obtenerTablaVend();
        tablaVendedor.setModel(modeloTabla);
        titulosTabla();     
    }
    
     private void titulosTabla(){
        tablaVendedor.getColumn(tablaVendedor.getColumnName(0)).setHeaderValue(" ");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(1)).setHeaderValue("Nombre");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(2)).setHeaderValue("Salario");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(3)).setHeaderValue("%Comisión");
        tablaVendedor.getColumn(tablaVendedor.getColumnName(4)).setHeaderValue("#Ventas");

        
        tablaVendedor.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaVendedor.getColumnModel().getColumn(0).setMinWidth(0);
        tablaVendedor.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaVendedor.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAlmacen = new javax.swing.JMenu();
        sMnuGestProd = new javax.swing.JMenuItem();
        sMnuRegPed = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        sMnuAgregarCl = new javax.swing.JMenuItem();
        sMnuRegVen = new javax.swing.JMenuItem();
        sMnuGestionarCl = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenu();
        sMnuAgregarProv = new javax.swing.JMenuItem();
        sMnuGestionarProv = new javax.swing.JMenuItem();
        mnuVendedores = new javax.swing.JMenu();
        sMnuAgVend = new javax.swing.JMenuItem();
        sMnuGestVend = new javax.swing.JMenuItem();
        mnuContabilidad = new javax.swing.JMenu();
        sMnuAgregarCta = new javax.swing.JMenuItem();
        smnuBalGen = new javax.swing.JMenuItem();
        sMnuEdoRes = new javax.swing.JMenuItem();
        sMnuFinanzas = new javax.swing.JMenuItem();
        mnuPeriodo = new javax.swing.JMenu();
        sMnuCerrPeriodo = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        sMnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendedores");

        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Salario", "% Comision", "# ventas"
            }
        ));
        jScrollPane1.setViewportView(tablaVendedor);

        jButton2.setText("Agregar");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(5, 0, 5, 20));

        mnuAlmacen.setText("Almacen");
        mnuAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuAlmacen.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuGestProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuGestProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestProd.setText("Existencias");
        sMnuGestProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestProdActionPerformed(evt);
            }
        });
        mnuAlmacen.add(sMnuGestProd);

        sMnuRegPed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        sMnuRegPed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuRegPed.setText("Registrar Pedido");
        sMnuRegPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuRegPedActionPerformed(evt);
            }
        });
        mnuAlmacen.add(sMnuRegPed);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Gestionar productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAlmacen.add(jMenuItem1);

        jMenuBar1.add(mnuAlmacen);

        mnuClientes.setText("Clientes");
        mnuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuClientes.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarCl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuAgregarCl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarCl.setText("Agregar Cliente");
        sMnuAgregarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarClActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuAgregarCl);

        sMnuRegVen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        sMnuRegVen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuRegVen.setText("Historial de ventas");
        sMnuRegVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuRegVenActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuRegVen);

        sMnuGestionarCl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        sMnuGestionarCl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestionarCl.setText("Operaciones");
        sMnuGestionarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestionarClActionPerformed(evt);
            }
        });
        mnuClientes.add(sMnuGestionarCl);

        jMenuBar1.add(mnuClientes);

        mnuProveedores.setText("Proveedores");
        mnuProveedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuProveedores.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarProv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarProv.setText("Agregar Proveedor");
        sMnuAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarProvActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuAgregarProv);

        sMnuGestionarProv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        sMnuGestionarProv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestionarProv.setText("Gestionar Proveedores");
        sMnuGestionarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestionarProvActionPerformed(evt);
            }
        });
        mnuProveedores.add(sMnuGestionarProv);

        jMenuBar1.add(mnuProveedores);

        mnuVendedores.setText("Vendedores");
        mnuVendedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuVendedores.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgVend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgVend.setText("Agregar vendedor");
        sMnuAgVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgVendActionPerformed(evt);
            }
        });
        mnuVendedores.add(sMnuAgVend);

        sMnuGestVend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        sMnuGestVend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuGestVend.setText("Gestionar vendedores");
        sMnuGestVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuGestVendActionPerformed(evt);
            }
        });
        mnuVendedores.add(sMnuGestVend);

        jMenuBar1.add(mnuVendedores);

        mnuContabilidad.setText("Contabilidad");
        mnuContabilidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuContabilidad.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuAgregarCta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuAgregarCta.setText("Agregar cuenta");
        sMnuAgregarCta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuAgregarCtaActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuAgregarCta);

        smnuBalGen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        smnuBalGen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smnuBalGen.setText("Balance General");
        smnuBalGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuBalGenActionPerformed(evt);
            }
        });
        mnuContabilidad.add(smnuBalGen);

        sMnuEdoRes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        sMnuEdoRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuEdoRes.setText("Estado de Resultados");
        sMnuEdoRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuEdoResActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuEdoRes);

        sMnuFinanzas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        sMnuFinanzas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuFinanzas.setText("Mando financiero");
        sMnuFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuFinanzasActionPerformed(evt);
            }
        });
        mnuContabilidad.add(sMnuFinanzas);

        jMenuBar1.add(mnuContabilidad);

        mnuPeriodo.setText("Periodos");
        mnuPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuPeriodo.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuCerrPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuCerrPeriodo.setText("Cerrar periodo");
        sMnuCerrPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuCerrPeriodoActionPerformed(evt);
            }
        });
        mnuPeriodo.add(sMnuCerrPeriodo);

        jMenuBar1.add(mnuPeriodo);

        mnuOpciones.setText("Opciones");
        mnuOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuOpciones.setMargin(new java.awt.Insets(0, 0, 0, 10));

        sMnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sMnuSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sMnuSalir.setText("Salir");
        sMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMnuSalirActionPerformed(evt);
            }
        });
        mnuOpciones.add(sMnuSalir);

        jMenuBar1.add(mnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sMnuGestProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestProdActionPerformed
        IntAlmacen v = new IntAlmacen();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestProdActionPerformed

    private void sMnuRegPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuRegPedActionPerformed
        IntSelectProv v = new IntSelectProv();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuRegPedActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IntProductos v = new IntProductos();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sMnuAgregarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarClActionPerformed
        IntAgregarCl v = new IntAgregarCl();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarClActionPerformed

    private void sMnuRegVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuRegVenActionPerformed
        IntHistoVenta v = new IntHistoVenta();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuRegVenActionPerformed

    private void sMnuGestionarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestionarClActionPerformed
        IntClientes v = new IntClientes();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestionarClActionPerformed

    private void sMnuAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarProvActionPerformed
        IntAgregarProv v = new IntAgregarProv();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarProvActionPerformed

    private void sMnuGestionarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestionarProvActionPerformed
        IntProveedores v = new IntProveedores();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestionarProvActionPerformed

    private void sMnuAgVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgVendActionPerformed
        IntAgregarVend v = new IntAgregarVend();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgVendActionPerformed

    private void sMnuGestVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuGestVendActionPerformed
        IntVendedores v = new IntVendedores();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuGestVendActionPerformed

    private void sMnuAgregarCtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuAgregarCtaActionPerformed
        IntAgregarCta v = new IntAgregarCta();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuAgregarCtaActionPerformed

    private void smnuBalGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuBalGenActionPerformed
        IntBalanceGral bg = new IntBalanceGral();
        bg.setVisible(true);
        dispose();
    }//GEN-LAST:event_smnuBalGenActionPerformed

    private void sMnuEdoResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuEdoResActionPerformed
        IntEdoRes edo = new IntEdoRes();
        edo.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuEdoResActionPerformed

    private void sMnuFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuFinanzasActionPerformed
        IntCarga c = new IntCarga();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_sMnuFinanzasActionPerformed

    private void sMnuCerrPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuCerrPeriodoActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(
            this, "¿Lo confirmas?");
        if (JOptionPane.OK_OPTION == confirmado){
            Utilidades uts = new Utilidades();
            String fecha = uts.obtFechaStringDMA();
            Secretaria mary = new Secretaria();

            if(mary.cierraPeriodo(fecha)){
                JOptionPane.showOptionDialog(this, "Periodo cerrado exitosamente", "Notificación", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
                IntCuentas c = new IntCuentas();
                c.setVisible(true);
                dispose();
            }else{
                JOptionPane.showOptionDialog(this, "Error al cerrar periodo", "Notificación", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" OK "},"OK");
            }
        }
    }//GEN-LAST:event_sMnuCerrPeriodoActionPerformed

    private void sMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMnuSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_sMnuSalirActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuAlmacen;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuContabilidad;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuPeriodo;
    private javax.swing.JMenu mnuProveedores;
    private javax.swing.JMenu mnuVendedores;
    private javax.swing.JMenuItem sMnuAgVend;
    private javax.swing.JMenuItem sMnuAgregarCl;
    private javax.swing.JMenuItem sMnuAgregarCta;
    private javax.swing.JMenuItem sMnuAgregarProv;
    private javax.swing.JMenuItem sMnuCerrPeriodo;
    private javax.swing.JMenuItem sMnuEdoRes;
    private javax.swing.JMenuItem sMnuFinanzas;
    private javax.swing.JMenuItem sMnuGestProd;
    private javax.swing.JMenuItem sMnuGestVend;
    private javax.swing.JMenuItem sMnuGestionarCl;
    private javax.swing.JMenuItem sMnuGestionarProv;
    private javax.swing.JMenuItem sMnuRegPed;
    private javax.swing.JMenuItem sMnuRegVen;
    private javax.swing.JMenuItem sMnuSalir;
    private javax.swing.JMenuItem smnuBalGen;
    private javax.swing.JTable tablaVendedor;
    // End of variables declaration//GEN-END:variables
}
